import { render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it } from 'vitest'
import App from './App'

/** A move is [section label 1-9, cell position 0-8], matching how the board reads on screen. */
type Move = [section: number, cell: number]

async function playMoves(user: ReturnType<typeof userEvent.setup>, moves: Move[]) {
  for (const [section, cell] of moves) {
    const group = screen.getByRole('group', { name: `Section ${section}` })
    // Query every cell (marked or not) so positions stay fixed - filtering to
    // only "Empty cell" would shift indices once a section has any marks.
    await user.click(within(group).getAllByRole('button')[cell])
  }
}

function overlayInSection(section: number) {
  const group = screen.getByRole('group', { name: `Section ${section}` })
  expect(within(group).queryAllByRole('button')).toHaveLength(0)
  return group
}

describe('App', () => {
  it('starts with player X and every section playable', () => {
    render(<App />)

    expect(screen.getByText(/player x's turn — play anywhere/i)).toBeInTheDocument()
    const cells = screen.getAllByRole('button', { name: 'Empty cell' })
    expect(cells).toHaveLength(81)
    cells.forEach((cell) => expect(cell).toBeEnabled())
  })

  it('routes the next player to the matching section after a move', async () => {
    const user = userEvent.setup()
    render(<App />)

    // Top-left cell (0) of section 3 (top-right) sends O to section 1 (top-left).
    await playMoves(user, [[3, 0]])

    expect(screen.getByText(/player o's turn — play in section 1/i)).toBeInTheDocument()
  })

  it('ignores clicks on a cell that is already marked', async () => {
    const user = userEvent.setup()
    render(<App />)

    await playMoves(user, [[3, 0]])
    const marked = screen.getByRole('button', { name: 'Cell marked X' })
    await user.click(marked)

    expect(marked).toBeDisabled()
    expect(screen.getByText(/player o's turn — play in section 1/i)).toBeInTheDocument()
    expect(screen.getAllByRole('button', { name: /^Cell marked/ })).toHaveLength(1)
  })

  it('does not let a player move outside the required section', async () => {
    const user = userEvent.setup()
    render(<App />)

    await playMoves(user, [[3, 0]]) // O must now play in section 1
    const elsewhere = within(screen.getByRole('group', { name: 'Section 9' })).getAllByRole(
      'button',
    )[0]
    await user.click(elsewhere)

    expect(elsewhere).toBeDisabled()
    expect(screen.getByText(/player o's turn — play in section 1/i)).toBeInTheDocument()
  })

  it('resets the board when New Game is clicked', async () => {
    const user = userEvent.setup()
    render(<App />)

    await playMoves(user, [[3, 0]])
    await user.click(screen.getByRole('button', { name: 'New Game' }))

    expect(screen.getByText(/player x's turn — play anywhere/i)).toBeInTheDocument()
    expect(screen.getAllByRole('button', { name: 'Empty cell' })).toHaveLength(81)
  })

  it('shows a winner overlay on a small board once it is won, and keeps routing correctly', async () => {
    const user = userEvent.setup()
    render(<App />)

    // X wins section 1 (top row) while O is bounced through other sections
    // by the cell-position routing rule.
    await playMoves(user, [
      [1, 0], // X
      [1, 4], // O
      [5, 5], // X
      [6, 0], // O
      [1, 1], // X
      [2, 0], // O
      [1, 2], // X completes the top row of section 1
    ])

    expect(within(overlayInSection(1)).getByText('X')).toBeInTheDocument()
    // Cell 2 was the last move, so O must play in section 3, which is still open.
    expect(screen.getByText(/player o's turn — play in section 3/i)).toBeInTheDocument()
  })

  // The two full games below were generated by an independent reference
  // implementation of the rules (not by this app's code), then replayed here
  // through the real UI. If any click were refused as illegal, the final
  // assertions would fail.
  it('plays a full game through the UI to an overall win, including free-choice turns', async () => {
    const user = userEvent.setup()
    render(<App />)

    await playMoves(user, [
      [5, 1],
      [2, 4],
      [5, 0],
      [1, 2],
      [3, 0],
      [1, 4],
      [5, 2],
      [3, 6],
      [7, 4],
    ])
    // Move 9 (cell 4) points at section 5, which X already won on moves 1-5,
    // so there is nothing to play there and O gets a free choice.
    expect(screen.getByText(/player o's turn — play anywhere/i)).toBeInTheDocument()

    await playMoves(user, [
      [1, 6],
      [7, 3],
      [4, 2],
      [3, 4],
      [9, 3],
      [4, 7],
      [8, 1],
      [2, 1],
      [2, 6],
      [7, 5],
      [6, 2],
      [3, 8],
    ])

    expect(screen.getByText('Player X wins!')).toBeInTheDocument()
    expect(within(overlayInSection(1)).getByText('O')).toBeInTheDocument()
    // X won the diagonal of sections 3, 5 and 7.
    for (const winningSection of [3, 5, 7]) {
      expect(within(overlayInSection(winningSection)).getByText('X')).toBeInTheDocument()
    }
    // Once the game is over, no cell anywhere can be played.
    screen.getAllByRole('button', { name: /cell/i }).forEach((cell) => expect(cell).toBeDisabled())

    await user.click(screen.getByRole('button', { name: 'New Game' }))
    expect(screen.getByText(/player x's turn — play anywhere/i)).toBeInTheDocument()
    expect(screen.getAllByRole('button', { name: 'Empty cell' })).toHaveLength(81)
  })

  it('plays a full game through the UI to a tie', async () => {
    const user = userEvent.setup()
    render(<App />)

    await playMoves(user, [
      [3, 3],
      [4, 2],
      [3, 5],
      [6, 8],
      [9, 1],
      [2, 5],
      [6, 6],
      [7, 1],
      [2, 6],
      [7, 2],
      [3, 4],
      [5, 7],
      [8, 0],
      [1, 3],
      [4, 6],
      [7, 0],
      [1, 8],
      [9, 6],
      [1, 4],
      [5, 6],
      [4, 8],
      [9, 2],
      [1, 0],
      [5, 8],
      [9, 8],
      [9, 4],
      [8, 5],
      [6, 7],
      [8, 8],
      [6, 5],
      [6, 1],
      [2, 4],
      [4, 7],
      [8, 7],
      [8, 1],
      [2, 3],
      [8, 2],
      [6, 2],
    ])

    expect(screen.getByText("It's a tie!")).toBeInTheDocument()
    // Every section was won (none tied), in a pattern with no line of three.
    const expectedWinners = ['X', 'O', 'X', 'X', 'O', 'O', 'O', 'X', 'O']
    expectedWinners.forEach((winner, index) => {
      expect(within(overlayInSection(index + 1)).getByText(winner)).toBeInTheDocument()
    })
    expect(screen.queryAllByRole('button', { name: /cell/i })).toHaveLength(0)
  })
})
